### ISSUE TITLE
Display of version in frontend

### ISSUE THREAD

**Issue by exp1338** [OStrama/weishaupt_modbus#10]
**Describe the bug**
Display of version in Frontend not working correctly? 

**To Reproduce**
Installed integration via HACS with version 0.0.7

**Expected behavior**
Version 0.0.7 should be displayed

**Screenshots**
![Screenshot 2024-10-19 194659](https://github.com/user-attachments/assets/06435842-ae90-4664-8c1f-0dbe027ef272)

**Additional context**
I hope you can fix it. Thanks for this integration!

**Comment by MadOne** [comment]
He just forgot to increase the version nuber in the manifest.json of the integration. When done, this is fixed in the next release

**Comment by OStrama** [comment]
Thanks! I swear not to forget this anymore ;-) 
I’m working on a new version to fix some of the issues

**Comment by MadOne** [comment]
Fixed in next version with https://github.com/OStrama/weishaupt_modbus/commit/f7f8c180790291f325efcafbf9fcd9f59e2e91d2
