### ISSUE TITLE
Implimenation of an icon for the integration?

### ISSUE THREAD

**Issue by exp1338** [OStrama/weishaupt_modbus#11]
**Is your feature request related to a problem? Please describe.**
Implimenation of an icon for the integration?

**Describe the solution you'd like**
Maybe a logo of Weishaupt is useable? 

**Describe alternatives you've considered**
Hopefully you can find a logo without any legal concern.

**Additional context**
![Screenshot 2024-10-19 195135](https://github.com/user-attachments/assets/2e3f17ac-8643-48eb-9582-bde65bafb78b)

**Comment by OStrama** [comment]
I forked this from MadOne, where also no icon was included. It seems that HA or at least HACS finds and assigns the icon automatically. 
I try to find out how icons can be used..

**Comment by MadOne** [comment]
My Integration had an addon. I think it is missing because you changed the integration name. The icon was uploaded to the ha-brands repository like described in the hacs developer docs for integration.

**Comment by MadOne** [comment]
https://github.com/MadOne/ha-brands/commit/ef7a426e5f5e3d85b865b4738dad5d9fdc8f1ac0
needs to be merged into [HA-Brands](https://github.com/home-assistant/brands) in case you like the icon and logos.

**Comment by MadOne** [comment]
@OStrama shall i start a pull request?

**Comment by OStrama** [comment]
Yes, that would be great!

**Comment by MadOne** [comment]
Fixed with https://github.com/OStrama/weishaupt_modbus/commit/92556c5ea590376fdedcf4ba51d69006494de441.
Should be part of the next version.
