### ISSUE TITLE
SG-Ready 1 via Modbus-TCP

### ISSUE THREAD

**Issue by exp1338** [OStrama/weishaupt_modbus#14]
**Is your feature request related to a problem? Please describe.**
Is there any chance to add the SG-Ready 1 Input via Modbus?
Regarding to this sheet https://docs.google.com/spreadsheets/d/1EZ3QgyB41xaXo4B5CfZe0Pi8KPwzIGzK/edit?gid=1810868580#gid=1810868580 there should be an input to activate SG-ready

**Describe the solution you'd like**
Add this Input Register
Bezeichnung | Format | APP-ID | Modbus | Register
SG-Ready 1 |   | 0xF000010A | 35 101 | Input

**Describe alternatives you've considered**
Just hardwired shelly/switch.

**Additional context**
Thanks for this integration!

**Comment by MadOne** [comment]
This value can be integrated. But is far is i remember the description is false and this value is read only. Can someone confirm that by try changing it?

**Comment by OStrama** [comment]
That would be also interesting for me ;-). Unfortunately, „input“ means „read only“ in this document, see the chart with statistics. „Holding RW“ are registers that can be modified. 
But if anybody finds a way to activate SG ready, we try to implement it.
Another way would be using the „Party/Pause“ or „WW-Push“ entities to accelerate the heater in case of sun via an automation..

**Comment by MadOne** [comment]
This is my solution:

![Bildschirmfoto vom 2024-10-25 19-09-29](https://github.com/user-attachments/assets/69797a84-cf29-417f-86a8-8add6406c7d9)

sensor:
  - platform: statistics
    name: "Power 60 minute average"
    entity_id: sensor.einspeisung_u_wp
    state_characteristic: mean
    max_age:
      minutes: 60

I add the power consumption of the heatpump and the outgoing power to the net.
If this is in average for the last hour over 3kW then i increase the Warm Water temperature to 55°C

If it drops i do the reverse.

**Comment by MadOne** [comment]
I made some progress on this:
![image](https://github.com/user-attachments/assets/22212223-3c3b-4360-a6bd-d9dac91a40bb)
Inputs should work correctly besides SGR2 is displayed false when SGR1 = SGR
When SGR1 = SGR then SGR2 should be SGR too.

When changing the output configuration there seems to happen nothing.
Can someone confirm that behavour? (With 0.0.8.pre11 or later)

**Comment by OStrama** [comment]
I‘ll have a look when back home..

**Comment by OStrama** [comment]
Back home ;-) I cannot really align the names here:
![image](https://github.com/user-attachments/assets/bc727638-d949-4ba3-8f65-c3814f6f9d4f)
with the configuration in WEM-Portal:
In:
![image](https://github.com/user-attachments/assets/3b39a64b-7e06-4e9c-85a8-f8f8532dfb44)
and Out:
![image](https://github.com/user-attachments/assets/d57a1ca2-4b36-46f0-840e-f231c9d8ee4f)

**Comment by MadOne** [comment]
I agreed, its hard. DE (? Digitaler Eingang?) should be correct. Sgr1 and 2 also. 

I tried to match the outputs, but when i change konfiguration nothing seems to happen at the modbus values

**Comment by kowi-k** [comment]
I figured it is read-only and does not even change if the heat pump is in SGR mode.
![image](https://github.com/user-attachments/assets/3aa95889-da36-4cd8-9d0d-00695255c510)
(top entity is the SG ready via modbus, below is the "Betriebsart" code read from modbus)

I have a shelly1 putting my heatpump in SGR mode.

**Comment by OStrama** [comment]
Hmm, there are some entities without values, like the annual statistic values. We display them as they are on the modbus..

**Comment by MadOne** [comment]
> Hmm, there are some entities without values, like the annual statistic values. We display them as they are on the modbus..

Here they have a value ("0"). As far is i know this is because weishaupt counts 365 days backwards. If the statistics are not that old it is 0. So the monthly statistics are ?30? days back, not the current month.

The firmware update reseted my statistics.

**Comment by MadOne** [comment]
There seems to be a problem with weishaupts implementation.
Closing this here.
If anybody has new information, feel free to post it.
