### ISSUE TITLE
use predefined duration values for entity number.warmwasser_push setting

### ISSUE THREAD

**Issue by Bertk** [OStrama/weishaupt_modbus#16]
**Improve usability using predefined values for "warmwasser_push" entity.**

The current implementation uses a slider to configure the time for push operation
<img width="330" alt="image" src="https://github.com/user-attachments/assets/a1e0a08c-b333-4490-9484-e85f9acd6b58">

The web portal uses predefined durations for this value which should also be used by modbus implementation.
<img width="325" alt="image" src="https://github.com/user-attachments/assets/4c765ada-27ea-451b-9848-787ecf14b99a">

**Comment by OStrama** [comment]
The Number has a step of 5, so it also would work. I'm not sure what is more comfortable..

**Comment by MadOne** [comment]
In my opinion the new version is more intuitive. Just like Party / Pause.

**Comment by Bertk** [comment]
I think 5 minute steps are OK and the predefined values can be selected on a iphone which is hard using a slider.

By the way, I will use 30 minutes or 60 minutes for the warm water push scenario. I use a 400 liter warm water tank and have a small heat pump.

**Comment by MadOne** [comment]
The heatpump only accepts 5min steps.

**Comment by OStrama** [comment]
I updated the ModbusItem, so that it works with Select entitiy now..

**Comment by MadOne** [comment]
It didnt work? I tested it befor i pushed the commit.

**Comment by OStrama** [comment]
It worked perfect, error was on my side, did not see git conflict...

**Comment by OStrama** [comment]
Added in 0.0.8pre5
