### ISSUE TITLE
add warn and error messages

### ISSUE THREAD

**Issue by backuprestore** [OStrama/weishaupt_modbus#22]
WBB12 and 20 Biblock

         StatusItem(1,"Kältemittelfühler Expansionsventil Eintritt (T1)"),
          StatusItem(2,"Luftansaugfühler (T2)"),
          StatusItem(3,"Wärmetauscherfühler AG Austritt (T3)"),
          StatusItem(4,"Verdichtersauggasfühler (T4)"),
          StatusItem(5,"EVI-Sauggasfühler (T5)"),
          StatusItem(6,"Kältemittelfühler IG Austritt (T6)"),
          StatusItem(7,"Ölsumpffühler (T7)"),
          StatusItem(8,"Expansionsventil EVI"),
          StatusItem(9,"Niederdrucksensor (P1)"),
          StatusItem(10,"Hochdrucksensor (P2)"),
          StatusItem(11,"Mitteldrucksensor (P3)"),
          StatusItem(12,"Expansionsventil Kühlen defekt"),
          StatusItem(13,"keine Kommunikation zum Inverter"),
          StatusItem(14,"keine Kommunikation zum Außengerät"),
          StatusItem(15,"Hochdruckschalter hat ausgelöst"),
          StatusItem(16,"Inverter gesperrt, da in den letzten 10 Stunden 10 Fehler aufgetreten sind"),
          StatusItem(17,"EEPROM Speicher-Fehler"),
          StatusItem(18,"keine Modbus-Kommunikation zwischen Regler EC und Steuerplatine Kältesatz"),
          StatusItem(19,"durch Inverter-Alarm Wärmepumpe abgeschaltet"),
          StatusItem(20,"Verdichter passt nicht zur Konfiguration"),
          StatusItem(21,"Niederdruck-Störung"),
          StatusItem(22,"zu geringe Überhitzung"),
          StatusItem(23,"zu hohe Überhitzung"),
          StatusItem(24,"EVI zu hohe Überhitzung"),
          StatusItem(25,"Kältemittelmenge zu niedrig"),
          StatusItem(26,"Hochdruck-Störung"),
          StatusItem(27,"Kondensationstemperatur zu niedrig"),
          StatusItem(28,"Kondensationstemperatur zu hoch"),
          StatusItem(29,"Verdampfungstemperatur zu niedrig"),
          StatusItem(30,"Verdampfungstemperatur zu hoch"),
          StatusItem(32,"Wärmepumpe nicht kompatibel"),
          StatusItem(33,"Regler EC hat keine Verbindung zum Erweiterungsmodul EM-HK"),
          StatusItem(40,"Volumenstrom zu gering"),
          StatusItem(41,"Spreizung LWT/Rücklauf negativ / Vierwegeventil schaltet nach dem Abtauen nicht zurück; nach 3 Warnungen verriegelt die Anlage)"),
          StatusItem(43,"Ventilator blockiert"),
          StatusItem(44,"Drehzahl Ventilator zu niedrig"),
          StatusItem(47,"Kommunikation Regler EC zu Steuerplatine Kältesatz fehlerhaft"),
          StatusItem(50,"Außenfühler (B1) unterbrochen"),
          StatusItem(51,"Außenfühler (B1) kurzgeschlossen"),
          StatusItem(52,"Weichenfühler (B2) unterbrochen"),
          StatusItem(53,"Weichenfühler (B2) kurzgeschlossen"),
          StatusItem(54,"Warmwasserfühler (B3) unterbrochen"),
          StatusItem(55,"Warmwasserfühler (B3) kurzgeschlossen"),
          StatusItem(56,"Vorlauffühler Verflüssiger (B4) unterbrochen"),
          StatusItem(57,"Vorlauffühler Verflüssiger (B4) kurzgeschlossen"),
          StatusItem(58,"Vorlauffühler (B7) unterbrochen"),
          StatusItem(59,"Vorlauffühler (B7) kurzgeschlossen"),
          StatusItem(60,"Rücklauffühler (B9) unterbrochen"),
          StatusItem(61,"Rücklauffühler (B9) kurzgeschlossen"),
          StatusItem(64,"Pufferfühler (B11) unterbrochen"),
          StatusItem(65,"Pufferfühler (B11) kurzgeschlossen"),
          StatusItem(66,"Mischerfühler regenerativ (B2.1) unterbrochen"),
          StatusItem(67,"Mischerfühler regenerativ (B2.1) kurzgeschlossen"),
          StatusItem(70,"Vorlauffühler Zweiter Heizkreis (B6.2) unterbrochen"),
          StatusItem(71,"Vorlauffühler Zweiter Heizkreis (B6.2) kurzgeschlossen"),
          StatusItem(72,"Fühler (T1.2) unterbrochen"),
          StatusItem(73,"Fühler (T1.2) kurzgeschlossen"),
          StatusItem(74,"Fühler (T2.2) unterbrochen"),
          StatusItem(75,"Fühler (T2.2) kurzgeschlossen"),
          StatusItem(90,"Analogeingang AE1 unterbrochen"),
          StatusItem(91,"Analogeingang AE1 kurzgeschlossen"),
          StatusItem(92,"Analogeingang AE2 unterbrochen"),
          StatusItem(93,"Analogeingang AE2 kurzgeschlossen"),
          StatusItem(94,"Analogeingang AE3 unterbrochen"),
          StatusItem(95,"Analogeingang AE3 kurzgeschlossen"),
          StatusItem(101,"Wärmepumpe wird außerhalb der Einsatzgrenzen betrieben"),
          StatusItem(102,"maximale Abtauzeit überschritten"),
          StatusItem(103,"Kommunikation Kältekreis fehlerhaft"),
          StatusItem(104,"Druckgastemperatur zu hoch"),
          StatusItem(105,"Stromaufnahme vom Inverter zu hoch"),
          StatusItem(106,"Stromaufnahme zu hoch"),
          StatusItem(107,"Gleichspannung am Inverter zu hoch"),
          StatusItem(108,"Gleichspannung am Inverter zu niedrig"),
          StatusItem(109,"Wärmepumpe wird außerhalb vom zulässigen Spannungsbereich betrieben"),
          StatusItem(110,"Wärmepumpe wird außerhalb vom zulässigen Spannungsbereich betrieben"),
          StatusItem(111,"Hochdruckschalter hat ausgelöst"),
          StatusItem(112,"Inverter ist überhitzt"),
          StatusItem(113,"Inverter ist überhitzt"),
          StatusItem(114,"Stellung vom Verdichtermotor kann nicht bestimmt werden"),
          StatusItem(117,"Gleichspannung am Inverter zu niedrig"),
          StatusItem(118,"Strom zwischen Inverter und Verdichter ist zu hoch"),
          StatusItem(119,"Stromaufnahme vom Verdichter zu hoch Zeitüberschreitung"),
          StatusItem(120,"Invertertemperatur zu hoch"),
          StatusItem(121,"Spannung am Inverter zu gering"),
          StatusItem(122,"Modbus-Konfigurationsfehler"),
          StatusItem(123,"keine Modbus-Verbindung"),
          StatusItem(124,"Druckgastemperatur zu hoch"),
          StatusItem(127,"Invertertemperatur zu hoch"),
          StatusItem(128,"Inverter ist überhitzt"),
          StatusItem(129,"Modbus-Kommunikation fehlerhaft"),
          StatusItem(130,"Modbus-Kommunikation fehlerhaft"),
          StatusItem(133,"Elektronikfehler"),
          StatusItem(135,"Hochdruckschalter defekt"),
          StatusItem(136,"Verdichter passt nicht zur Konfiguration"),
          StatusItem(137,"Hochdruckschalter passt nicht zur Konfiguration"),
          StatusItem(140,"Druckgastemperatur zu niedrig"),
          StatusItem(143,"Invertertemperatur zu niedrig"),
StatusItem(144,"Drosselspulentemperatur zu niedrig"),
StatusItem(150,"Verdichter Stromsensor Phase U Fehler"),
StatusItem(151,"Verdichter Stromsensor Phase V Fehler"),
StatusItem(152,"Verdichter Stromsensor Phase W Fehler Spannungsversorgung von Eingangsklemme"),
StatusItem(153,"Stromsensor Fehler"),
StatusItem(154,"Inverter Temperatursensor Fehler"),
StatusItem(155,"Temperatursensor Fehler"),
StatusItem(156,"Druckgasfühler (DT)"),
StatusItem(157,"keine Kommunikation zur Steuerplatine Kältesatz"),
StatusItem(158,"EEPROM-Speicher-Fehler"),
StatusItem(159,"Stromaufnahme zu hoch"),
StatusItem(160,"Wärmepumpe wird außerhalb vom zulässigen Spannungsbereich betrieben"),
StatusItem(161,"Wärmepumpe wird außerhalb vom zulässigen Spannungsbereich betriebe"),n
StatusItem(162,"Gleichspannung am Inverter zu hoch"),
StatusItem(163,"Gleichspannung am Inverter zu niedrig"),
StatusItem(164,"Hochdruckschalter hat ausgelöst"),
StatusItem(165,"Phase zwischen Eingang und Verdichter unterbrochen"),
StatusItem(166,"Inverter überhitzt"),
StatusItem(167,"Inverter überhitzt"),
StatusItem(168,"Konfigurationsfehler Verdichter"),
StatusItem(169,"Stromaufnahme vom Verdichter zu hoch"),
StatusItem(170,"Verdichter Phase U Überspannung"),
StatusItem(171,"Verdichter Phase V Überspannung"),
StatusItem(172,"Verdichter Phase W Überspannung"),
StatusItem(173,"Phasenausfall am Verdichter"),
StatusItem(174,"Verdichter blockiert"),
StatusItem(175,"Verdichter startet nicht"),
StatusItem(176,"Unregelmäßige Spannungsversorgung vom Inverter"),
StatusItem(177,"Verdichter überlastet"),
StatusItem(178,"Temperatur am Druckgasfühler (DT) zu hoch"),
StatusItem(179,"Temperatur am Inverter"),
StatusItem(180,"Verdichter blockiert"),
StatusItem(181,"Verdichter blockiert"),
StatusItem(182,"Stromaufnahme zu hoch"),
StatusItem(183,"Stromaufnahme zu hoch"),
StatusItem(184,"Spannung zu hoch"),

**Comment by OStrama** [comment]
Are you willing to contribute directly? We could add you as a coworker to the repro.

**Comment by backuprestore** [comment]
Hi,

thank you for the request. unfortunately i'm changing my job position, so time is limited for the next month, but i'll try to forward my findings to you over github.

thank you for your work!
Maik


________________________________
Von: OStrama ***@***.***>
Gesendet: Dienstag, 29. Oktober 2024 22:35
An: OStrama/weishaupt_modbus ***@***.***>
Cc: backuprestore ***@***.***>; Author ***@***.***>
Betreff: Re: [OStrama/weishaupt_modbus] add warn and error messages (Issue #22)


Are you willing to contribute directly? We could add you as a coworker to the repro.

**Comment by OStrama** [comment]
O.K. Understand. Wish you all the best for your new Job role!

**Comment by OStrama** [comment]
Done in next version!

**Comment by MadOne** [comment]
What is with the items > 144?

**Comment by backuprestore** [comment]
They are valid... Was a formating issue with GitHub.. Just add them

Gesendet von Outlook für Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by OStrama** [comment]
Already added..
