### ISSUE TITLE
Enable edit of config entry

### ISSUE THREAD

**Issue by MadOne** [OStrama/weishaupt_modbus#23]
**Is your feature request related to a problem? Please describe.**
When testing, changing or adding prefix we always have to remove the entry and create a new one.
Editing the existing entry would be much mor convenient.

**Describe the solution you'd like**
Enable the edit path in config flow acording to [this](https://developers.home-assistant.io/docs/config_entries_config_flow_handler)

**Describe alternatives you've considered**
Further remove and create new entries

**Comment by OStrama** [comment]
that's what async_step_reconfigure() seems to be used for. I made a try but it did not work...

**Comment by MadOne** [comment]
I also tried. Didnt work either. I managed to pull up the edit but it is not prefilled with the current settings. Saving results in new devices so it writes new values instead of updating it.

**Comment by MadOne** [comment]
I managed to prefill the edit mask. Host and port can be changed, but the rest of the values seem to not update.

**Comment by MadOne** [comment]
I had to update ha in dev contains to make this work.  Maybe we have to wait for a new ha version.

**Comment by MadOne** [comment]
https://developers.home-assistant.io/blog/2024/10/21/reauth-reconfigure-helpers/

**Comment by OStrama** [comment]
Hmm, is there an older equivalent possible? I do not want to loose all users with versions that are a bit older..

**Comment by MadOne** [comment]
We could just try and catch: ha version to old

There is an old way described too. I will look into this.

**Comment by OStrama** [comment]
I tested it. Works so far when taking the following into account:

- Changing device postfix will duplicate devices
- changing entity names will also duplicate them

I made a mistake in the config entry update. Did not distinguish between version 1,2,3,4 but always overwrote entries when old version was detected. I do this now granularily.

**Comment by MadOne** [comment]
> * Changing device postfix will duplicate devices

This changes the unique entity id:
self._attr_unique_id = dev_prefix + self._modbus_item.name + dev_postfix

> * changing entity names will also duplicate them

You mean the last 2 options? This only changes the name, not the unique name. So no new entitiys / devices should be created.
