### ISSUE TITLE
Adjustment "Pumpe Leistung Heizen" possible? 

### ISSUE THREAD

**Issue by exp1338** [OStrama/weishaupt_modbus#26]
**Is your feature request related to a problem? Please describe.**
Want to adjust "Pumpe Leistung Heizen		PID 226	  Register 43 103	Holding R/W"

**Describe the solution you'd like**
Is there any chance to change it via Modus TCP?

**Describe alternatives you've considered**
Today i set it up via WEMPortal

**Additional context**
Context: Currently try to in/decrease power to avoid clocking because our heatpump seems way to large. Want to setup power based on temperature.

**Comment by MadOne** [comment]
Where do you get this Modbus Register information from?
We have: 43103, "Pumpe Einschaltart" from https://docs.google.com/spreadsheets/d/1EZ3QgyB41xaXo4B5CfZe0Pi8KPwzIGzK/edit?gid=1730751621#gid=1730751621

**Comment by exp1338** [comment]
This one: https://docs.google.com/spreadsheets/d/1EZ3QgyB41xaXo4B5CfZe0Pi8KPwzIGzK/edit?gid=636734480#gid=636734480

**Comment by MadOne** [comment]
![image](https://github.com/user-attachments/assets/5a350130-d088-4bea-8b79-91cef76f49b9)
![image](https://github.com/user-attachments/assets/2aa206a6-ce91-446a-a873-2ae5fa7342ce)
We have an error here. Acording to the doku 43 101 is Konfiguration  @ Ruhemodus.

So our integration might be right.

@OStrama 
We could easily change the entitys to number and have sliders to change the values.

**Comment by MadOne** [comment]
@OStrama 
What about making 3 levels:
1. Read only: Just to monitor the heatpump. No writing modbus registers possible.
2. Balanced: Open uncritical options for writing
3. 3. "I think i know what i am doing": Open every possible option for writing.

@exp1338 : In the meantime you could go to hpconst.py and update this line:
`    ModbusItem( 43104, "Sollwert Pumpe Leistung Heizen", FORMATS.PERCENTAGE, TYPES.NUMBER_RO, DEVICES.WP, RANGE_PERCENTAGE),`
to
`    ModbusItem( 43104, "Sollwert Pumpe Leistung Heizen", FORMATS.PERCENTAGE, TYPES.NUMBER, DEVICES.WP, RANGE_PERCENTAGE),`

**Comment by maddinhome** [comment]
Can you set a warning for these settings? or only after entering OK that the settings are now dangerous and you should know what you are doing there. It would also be important to indicate that you are not responsible for the misconfiguration.

**Comment by OStrama** [comment]
Yes, this could be an option… 
@MadOne : Do you know how to implement a popup when changing a value? (It‘s also about the touch interface on the phone. There‘s a risk that you change a value by mistake by swiping on the screen..)

**Comment by MadOne** [comment]
@OStrama You mean on every entity itself? No i dont know.

**Comment by MadOne** [comment]
I googled quite a while and found some custom cards that allow this. But the user would have to set this up on his own. At the moment i see no possibility to define this in our integration.

A possibility would be: 
Make a switch witch enables adminmode for 1 minute
The dangerous entitiys check if admin mode is enabled, elso on change setback to value from modbus. (no change)

**Comment by MadOne** [comment]
@OStrama any thoughts on this?

**Comment by MadOne** [comment]
For now we dont see a safe way to open these values for manipulation. You can edit the hpconst.py file as described above if you really need this functionality.

I will close this now, but feel free to reopen if you have new suggestions/info.
