### ISSUE TITLE
Failed to set up connection with heat pump

### ISSUE THREAD

**Issue by bcumps** [OStrama/weishaupt_modbus#3]
Failed to set up connection with heat pump. Log file in attachment.

[home-assistant_weishaupt_wbb_2024-10-11T07-01-19.161Z.log](https://github.com/user-attachments/files/17339513/home-assistant_weishaupt_wbb_2024-10-11T07-01-19.161Z.log)

**Comment by OStrama** [comment]
Please check out 0.0.2. I added scipy as requirement.

**Comment by OStrama** [comment]
Please check out 0.0.3. I added scipy as requirement. (in 0.0.2 code base was not yet synched..)

**Comment by OStrama** [comment]
Did the last version solve the issue?

**Comment by bcumps** [comment]
No, it did not. Got noew the error that package scipy==1.14.1 can't be installed.

[home-assistant_2024-10-12T12-09-03.073Z.log](https://github.com/user-attachments/files/17349962/home-assistant_2024-10-12T12-09-03.073Z.log)

**Comment by OStrama** [comment]
Ah, OK,Then please try the latest version. I removed scipy and use Chebycheff polynom from numoy. This should work..

**Comment by bcumps** [comment]
Indeed, it does! Thank you.

**Comment by OStrama** [comment]
OK, thanks for the info! Then I close this issue.
