### ISSUE TITLE
Translation possible?

### ISSUE THREAD

**Issue by StijnVdd** [OStrama/weishaupt_modbus#30]
Hi,

First of all, thanks a lot for this integration!

Would it be possible to provide a translation for all the entities and their state ?
I've been renaming the entity names in HA and this mostly does meet my requirement, but the states of the entities are not changeable (at least not without defining a template entity or something like that)

I would therefore like to suggest the possibility to configure the language of integration. For example via a setting or by using the same language as the HA frontend.

I would love to help out with the translation files.

Thanks a lot the the consideration.

**Comment by MadOne** [comment]
Value Translation is possible, but a lot of work. 

Entity renaming is also possible but won't work with our current dynamic prefix system.

**Comment by OStrama** [comment]
Adding translation possibility of all names and values will be part of a new version.

Inbeteween you can help yourself as follows:

1. In principle, all of the fixed strings are concentrated in the file hpconst.py. 
2. You can simply edit the strings in this file to have all values in the language you prefer.
3. If you do so, it would be great to send us the modified file (please **no direct pull request**, since it will flip the default language ;-)), so that we cann use this as input for future translations.

**Comment by StijnVdd** [comment]
Thanks a lot for the feedback!

With the help of some AI, I've translated the file in Dutch.
A lot of translations are not 100% ok, but I'll tweak those on the go.

Please find attached the translated file.

After changing this file and restarting HA, the integration created completely new entities (and thus entity_ids) causing the few automations I had build to break.

May I suggest to keep this in mind when developing this translation feature?
Suggestion: keep the entity IDs in English (a bit more universal) and allow the name to change based on the language configuration.

I assume this translation feature will result in a rather large refactor, so another suggestion I would like to make is the possibility to define icons in the hpconst.py file. 

[hpconst_NL.zip](https://github.com/user-attachments/files/17738015/hpconst_NL.zip)

**Comment by OStrama** [comment]
For the next version, we can include entity names and states as described here:

https://developers.home-assistant.io/docs/internationalization/core

But we have to look how to handle pre and postfixes..

**Comment by MadOne** [comment]
Im already working on the translation feature. It will NOT change the "unique id" witch HA take for statistics and translate the name.

But we have to put EVERY sensor in a json like this:
        "Fehlerfrei": {
          "state": {
            "Fehler aktiv": "Fehler aktiv",
            "Störungsfreier Betrieb": "Störungsfreier Betrieb",
          },
          "name": "Fehlerfrei"
        }

As you can imagine this is verry time consuming, so please be patient.

**Comment by OStrama** [comment]
@StijnVdd  thanks for the file. I hope that the entity IDs will preserve when using the method described in the link in my last post. (It‘s my 1st integration, have to learn a lot..)
When back home I do a try with putting some sensor translations in the json files..

**Comment by OStrama** [comment]
> Im already working on the translation feature. It will NOT change the "unique id" witch HA take for statistics and translate the name.
> 
> But we have to put EVERY sensor in a json like this: "Fehlerfrei": { "state": { "Fehler aktiv": "Fehler aktiv", "Störungsfreier Betrieb": "Störungsfreier Betrieb", }, "name": "Fehlerfrei" }
> 
> As you can imagine this is verry time consuming, so please be patient.

A kind of coincidence ;-)

**Comment by MadOne** [comment]
@OStrama :
I created a new branch for this, as it breaks all entity names as long as the string.json and de.json are not complete.

**Comment by OStrama** [comment]
Maybe, it‘s faster to write a little python script that crunches through the StatusItem lists and builds the json file automatically ;-)

**Comment by MadOne** [comment]
Can you read my mind? Scary ;)

**Comment by MadOne** [comment]
I have a version we can test. But can't push from here in work. Will Push when i am at home. 

Prefix should work with {placeholder}

**Comment by StijnVdd** [comment]
Once pushed, I'll give it a try. Looking forward to it

**Comment by MadOne** [comment]
@StijnVdd : No build to test for you yet. Still working on it, sorry.

@OStrama: I made a generation function in __init__.py. We have to copy strings manually by now.
For testing i copied the strings.json to en.json and de.json. Not sure if there was a translation yet.

I am working on a automatical generation of strings.json and the {place_holder} now.

**Comment by MadOne** [comment]
@OStrama : I finally finished the translation system. Can you please  also check if it is working as expected?

**Comment by OStrama** [comment]
I tested the files that were checked in. To see what happens, I translated some of the entities in en.json into English.

The entity names seem to be translated. However, the name of the selections of a select entity do not change:

        "select": {
            "hz_betriebsart": {
                "name": "Operation mode",
                "state": {
                    "hz_betriebsart_absenk": "Lowering mode",
                    "hz_betriebsart_auto": "Automatic",
                    "hz_betriebsart_normal": "Normal",
                    "hz_betriebsart_standy": "Standby",
                    "hz_betriebsat_komfort": "Comfort"
                }
            },

![image](https://github.com/user-attachments/assets/a64fba90-dd42-4630-a907-aecf286648bd)

I checked out "translation"

**Comment by OStrama** [comment]
Maybe, it also would make sense to add translations to the devices, like this:

    "device":{
        "System": {"name": "System"},
        "Wärmepumpe": {"name": "Heat pump"},
        "Warmwasser": {"name": "Hot water"},
        "Heizkreis": {"name": "Heating circuit"},
        "Heizkreis2": {"name": "Heating circuit2"},
        "Heizkreis3": {"name": "Heating circuit3"},
        "Heizkreis4": {"name": "Heating circuit4"},
        "Heizkreis5": {"name": "Heating circuit5"},
        "2. Wärmeerzeuger": {"name": "2nd heat source"},
        "Statistik": {"name": "Statistics"},
        "Unknown": {"name": "Unknown"},
        "Eingänge/Ausgänge": {"name": "Input/output"}
    },

**Comment by OStrama** [comment]
Another point. If I look at:

    ModbusItem( address=30001, name="Aussentemperatur", mformat=FORMATS.TEMPERATUR, mtype=TYPES.SENSOR, device=DEVICES.SYS, resultlist=TEMPRANGE_STD, translation_key="aussentemp"),

And the usage of the name, it looks as if the name of the modbus item itself is not longer used. Shouldn't we completely replace it by the translation key or generate one of them automatically? Or do you need both to cretae strins.json?

**Comment by MadOne** [comment]
> Maybe, it also would make sense to add translations to the devices, like this:
> 
>     "device":{
>         "System": {"name": "System"},
>         "Wärmepumpe": {"name": "Heat pump"},
>         "Warmwasser": {"name": "Hot water"},
>         "Heizkreis": {"name": "Heating circuit"},
>         "Heizkreis2": {"name": "Heating circuit2"},
>         "Heizkreis3": {"name": "Heating circuit3"},
>         "Heizkreis4": {"name": "Heating circuit4"},
>         "Heizkreis5": {"name": "Heating circuit5"},
>         "2. Wärmeerzeuger": {"name": "2nd heat source"},
>         "Statistik": {"name": "Statistics"},
>         "Unknown": {"name": "Unknown"},
>         "Eingänge/Ausgänge": {"name": "Input/output"}
>     },

> Yes we should do this!

**Comment by MadOne** [comment]
> Another point. If I look at:
> 
>     ModbusItem( address=30001, name="Aussentemperatur", mformat=FORMATS.TEMPERATUR, mtype=TYPES.SENSOR, device=DEVICES.SYS, resultlist=TEMPRANGE_STD, translation_key="aussentemp"),
> 
> And the usage of the name, it looks as if the name of the modbus item itself is not longer used. Shouldn't we completely replace it by the translation key or generate one of them automatically? Or do you need both to cretae strins.json?

At the moment i use the name to gereate the strings.json. When the translation system is complete, we can erase the names.

**Comment by OStrama** [comment]
I found a way also to translate the list entries..

**Comment by MadOne** [comment]
Please push it.

**Comment by OStrama** [comment]
done ;-)

**Comment by OStrama** [comment]
it was basically using translation_key as strings here, too..

**Comment by MadOne** [comment]
![Bildschirmfoto vom 2024-11-17 14-43-45](https://github.com/user-attachments/assets/2348e66d-d61e-4500-91ce-b9aea20c8da3)

Seems to not work for me.

**Comment by OStrama** [comment]
switch your language to english. I translated the English version

**Comment by MadOne** [comment]
I was on a similar path, but changed the text_from_number function whitch seems to break something else.
Oh of course. I edited the german version for testing but overwrote with pull.

This looks good to me. So only the devices are missing and perhaps the prefix system

**Comment by OStrama** [comment]
text_from_number is also used to get text of error messages etc. When we put all in translation system, we could get rid of one of them..

**Comment by OStrama** [comment]
But it seems to work, too:

![image](https://github.com/user-attachments/assets/a89c06bb-2c30-4667-a417-c454d5db3e32)

**Comment by MadOne** [comment]
You have to be carefull with your translation_key values:

Error: R] [TRANSLATIONS] Invalid strings.json: Invalid translation key 'System', need to be [a-z0-9-_]+ and cannot start or end with a hyphen or underscore. for dictionary value @ data['device']. Got {'System': {'name': 'System'}, 'Wärmepumpe': {'name': 'Heat pump'}, 'Warmwasser': {'name': 'Hot water'}, 'Heizkreis': {'name': 'Heating circuit'}, 'Heizkreis2': {'name': 'Heating circuit2'}, 'Heizkreis3': {'name': 'Heating circuit3'}, 'Heizkreis4': {'name': 'Heating circuit4'}, 'Heizkreis5': {'name': 'Heating circuit5'}, '2. Wärmeerzeuger': {'name': '2nd heat source'}, 'Statistik': {'name': 'Statistics'}, 'Unknown': {'name': 'Unknown'}, 'Eingänge/Ausgänge': {'name': 'Input/output'}}

The hacs check complains: Invalid translation key 'System', need to be [a-z0-9-_]+ and cannot start or end with a hyphen or underscore.

This is why i had to recreate the translation_key. Before i had just copied the name over. But his HACS check won't allow that. Thats the reason why you probably got 20 emails ;)

**Comment by OStrama** [comment]
Yes, already corrected..

**Comment by OStrama** [comment]
Got it:
![image](https://github.com/user-attachments/assets/01b9400a-dfab-4d97-be0b-ff970dd98929)
But it will again replicate all device entries...

**Comment by OStrama** [comment]
But entities stay as they are, so we could use this..
Will check in in a minute..

**Comment by OStrama** [comment]
done ;-)

**Comment by OStrama** [comment]
I completely translated en.json. @StijnVdd : What about adding a file nl.json ;-)

**Comment by OStrama** [comment]
@MadOne What do you think, should we try to merge back translation to main?

**Comment by MadOne** [comment]
> @MadOne What do you think, should we try to merge back translation to main?
> 

Not sure if we should fix the prefix system first.

**Comment by OStrama** [comment]
Ah yes, makes sense. I saw on some source codes in core constructs like this:

  "config": {
    "step": {
      "user": {
        "title": "Fill in your Abode login information",
        "data": {
          "username": "[%key:common::config_flow::data::email%]",
          "password": "[%key:common::config_flow::data::password%]"
        }
      },

I do not really understand the syntax, but it seems that there's a way to use variables in names.

Otherwise, we have to find out what method of the entity class does the translation and overwrite it..

**Comment by MadOne** [comment]
As far as i know this are official home assistant strings.

**Comment by MadOne** [comment]
Or shared strings:
See https://developers.home-assistant.io/docs/internationalization/core/

**Comment by OStrama** [comment]
... or the brute-force method: Overwriting _device_class_name_helper() in SensorEntity and thwe others ;-)

    def _device_class_name_helper(
        self,
        component_translations: dict[str, str],
    ) -> str | None:
        """Return a decorated translated name of the entity based on its device class."""
        name = super()._device_class_name_helper(component_translations)

        if name is None:
            return name

        dev_postfix = ""
        dev_postfix = "_" + self._config_entry.data[CONF_DEVICE_POSTFIX]

        if dev_postfix == "_":
            dev_postfix = ""

        dev_prefix = CONST.DEF_PREFIX
        dev_prefix = self._config_entry.data[CONF_PREFIX]

        if self._config_entry.data[CONF_NAME_DEVICE_PREFIX]:
            name_device_prefix = self._config_entry.data[CONF_PREFIX] + "_"
        else:
            name_device_prefix = ""

        if self._config_entry.data[CONF_NAME_TOPIC_PREFIX]:
            name_topic_prefix = reverse_device_list[self._modbus_item.device] + "_"
        else:
            name_topic_prefix = ""

        name_prefix = name_topic_prefix + name_device_prefix
        complete_name = name_prefix + name

        return complete_name

**Comment by OStrama** [comment]
Looks a bit weird, because I made some mistakes in setting up the name..

![image](https://github.com/user-attachments/assets/7aa8534b-a71b-4613-a234-256271c70b5c)

**Comment by MadOne** [comment]
Looks a bit hacky to me. I think i got it with this:
https://developers.home-assistant.io/blog/2024/01/19/entity-translations-placeholders/

**Comment by OStrama** [comment]
OK, then delete the helper function to avoid interference..

**Comment by MadOne** [comment]
I have no working solution yet but this looks very promising. But its good to have a backup strategy.

Could you please look at [this](https://github.com/OStrama/weishaupt_modbus/issues/42)?
I would love to have this integration in the default hacs.

**Comment by OStrama** [comment]
Yes, sure!

**Comment by OStrama** [comment]
I think you should delete this function in entities.py 

    def _device_class_name_helper()

Then maybe the reverse_device_list was changed and could cause an issue..

**Comment by MadOne** [comment]
Translation will be possible in the next release.

**Comment by StijnVdd** [comment]
Hi,

I just downloaded the most recent version of the integration.
How can I contribute to the 'dutch' translation ?

**Comment by MadOne** [comment]
Hi,
you can take one of the following files:
strings.json
translation/en.json
translation/de.json and translate the strings.
Strings with underscore are most likely translation_keys and are not allowed to change.

We did not aktivate the translation yet, due to an entity naming issue. Anyways you can already start translaing.

**Comment by StijnVdd** [comment]
I'll translate the strings.json to dutch.
It that the one used by default for now ?

Is it correct the entity ID will always be in German and the 'translation' changes just the name?

**Comment by MadOne** [comment]
I created a new release UNSTABLE_1.0.2_Translation_UNSTABLE.

Be aware, this can create new devices and entitys, thus create new sensor history.
If you don't care about your sensor history you can use this whithout risk.

**Comment by StijnVdd** [comment]
Thanks a lot.

I installed this version and replaced the strings.json with my own version (dutch). I also added the nl.json in the translation folder but the integration is not picking up my file.

I do notice the entity IDs changes to english an no longer are in german.

I'll test a bit more and provide more feedback.

How is the language selected?

**Comment by MadOne** [comment]
Leave string.json and place your files in the translation folder. Language is taken from your home assistant.  You may need to restart ha for change of language

**Comment by OStrama** [comment]
Hi, please use version 1.0.4pre. In this version translation is enabled.
Please enable option „use old name style“ when updating from a former version.

**Comment by OStrama** [comment]
Yesterday I did some investigation about how to update an existing installation to the new entity ID naming scheme which has to be used to enable translations. 

Unfortunately, I did not find a reliable automatic way to do the renaming from within the integration. 
So I'd suggest first to make a new start with the new namestyle. 
This will crash the old statistics. If you want to keep it, I'd suggest and also add to the readme is the following process:

- Update to the version 1.0.4 when released. (You can test the procedure with 1.0.4pre2)
- Reconfigure the integration: Disable the option "Use old name style"
- restart HA: When setting up the entities, a file called list_names.json will be created in the integration's directory
- download this file and put it in a directory together with the little tool you can find here: https://github.com/OStrama/weishaupt_modbus/tree/rename_entities/rename_tool. It is based on https://github.com/saladpanda/homeassistant-entity-renamer and additionally allows usage of the json file
- update the config.py of the tool with your HA's IP address and the access token
- run the tool, the entities will be renamed.
- now you can switch the integration to new name style completely. I deleted and reinstalled it to make sure that all entities are assignet the right way
- perhaps you'd need to update some dashboards etc.

Please let me know what you think about it.

**Comment by OStrama** [comment]
I released 1.0.4pre3.

This version should do the migration of the entities automatically. After updating and restarting it runs through the entities and renames them to the new name scheme. Statistics should be moved to the new name, too. It only could be possible that dashboards, template sensors or automations and the energy dashboard need to be updated.
Note: When you come from 1.0.4pre2 and you used the option „old name style“, please leave it activated for the update. The new versions will ignore this flag from now on.

**Comment by OStrama** [comment]
1.0.4 with translation support released.

**Comment by MadOne** [comment]
@StijnVdd : Could you please give us your translated files so we could integrate them for other users?.
