### ISSUE TITLE
Warmwasser Push select should use white space to separate value and dimension

### ISSUE THREAD

**Issue by Bertk** [OStrama/weishaupt_modbus#33]
**Describe the bug**
Warmwasser Push select should use white space to separate value and dimension (cosmetic issue)

**Screenshots**
<img width="269" alt="image" src="https://github.com/user-attachments/assets/f508a97c-6db6-47b1-a546-6ed0c340c528">

**Desktop (please complete the following information):**
 - OS: Windows 11 Pro 24H2 (26100.2314)
 - edge V130.0.2849.80

**Smartphone (please complete the following information):**
 - Device: iPhone12
 - OS: iOS17.7.1
 - HA app 
 - Version 2024.9.4

**Additional context**
n.a.

**Comment by OStrama** [comment]
Thanks for the hint, will be fixed in next update.

**Comment by OStrama** [comment]
Maybe, we should use the minute constant from HA Const..

**Comment by Bertk** [comment]
This is always a good idea.

**Comment by OStrama** [comment]
Fixed in 1.0.1
