### ISSUE TITLE
Many values "unknown" since update to 1.0.0

### ISSUE THREAD

**Issue by l3nkz** [OStrama/weishaupt_modbus#34]
**Describe the bug**
I updated two days ago to version 1.0.0. According to the update instructions, I deleted the old version (0.0.6) and installed it completely new from scratch. 
Unfortunately since the update, quite a number of sensors that I usually use (Rücklauftemperatur, Leistungsanforderung, ...) are not available anymore.

**Comment by OStrama** [comment]
Are they available under a different name ore completely missing? 
when adding a new device, sometimes it‘s necessary to press F5 in the browser to see all entities.
However, when they are completely missing and had valid values before this sounds strange..

**Comment by l3nkz** [comment]
The entities exist, but they don't have a value.

**Comment by OStrama** [comment]
Could you make a screenshot?

**Comment by l3nkz** [comment]
![Screenshot_20241114-204326_Home_Assistant.png](https://github.com/user-attachments/assets/6cce035f-7c3c-44cd-83e8-23e0669127ac)

I also found something in the log which might be related ...

```
This error originated from a custom integration.

Logger: homeassistant
Source: custom_components/weishaupt_modbus/entities.py:358
integration: Weishaupt heat pump (documentation, issues)
First occurred: November 12, 2024, 22:52:26 (5523 occurrences)
Last logged: 20:53:26

Error doing job: Task exception was never retrieved (None)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 266, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 481, in _async_refresh
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 176, in async_update_listeners
    update_callback()
  File "/config/custom_components/weishaupt_modbus/entities.py", line 334, in _handle_coordinator_update
    self._attr_native_value = self.translate_val(self._modbus_item.state)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/weishaupt_modbus/entities.py", line 358, in translate_val
    val_x = self.calc_temperature(val[1]) / 10
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~
TypeError: unsupported operand type(s) for /: 'NoneType' and 'int'
```

**Comment by OStrama** [comment]
All sensor values are missing, the Number_RO exist..
The error in the log is a result of it, since it calculates the heat power from some sensor values.
@MadOne  any idea why the sensors fail?

**Comment by MadOne** [comment]
Maybe the calculated sensor? A problem with the kennfeld?

**Comment by OStrama** [comment]
Then the others would be present. I‘ll do an update with some debug logging later today..

**Comment by OStrama** [comment]
Could you please download version 1.0.0deb1? It‘s a pre-release so you would need to select it in HACS manually. I did not change anything beside adding some debug traces.

After HA restart please do the following:

1. open HA in browser, not in the app
2. Enable debug log of the integration
3. Reload the integration using the three dot menu of it
4. Disable debug log
5. Now the browser should download a log file. Please send this to us.

Thanks in advance!

**Comment by maddinhome** [comment]
Here is my logbook from a WSB 8 configured with the kennfield file for the WSB 8

[home-assistant_weishaupt_modbus_2024-11-15T12-30-53.999Z.log](https://github.com/user-attachments/files/17776807/home-assistant_weishaupt_modbus_2024-11-15T12-30-53.999Z.log)

I hope this is helpful.

**Comment by maddinhome** [comment]
Not all of them, but I don't think anything important is missing. It's just unpleasant when there are question marks or a value that you can't do anything with.

![Screenshot 2024-11-15 173510](https://github.com/user-attachments/assets/5d43fb9b-f3d0-43cb-9f12-75c1f8cb197d)
![Screenshot 2024-11-15 173700](https://github.com/user-attachments/assets/8b35dc3e-d265-4dcb-9876-b01dab0603bb)
![Screenshot 2024-11-15 173756](https://github.com/user-attachments/assets/570ddc31-4fac-41ee-af92-5e64ecf9e00a)
![Screenshot 2024-11-15 173826](https://github.com/user-attachments/assets/4b951cc3-b9dc-48a1-b30f-8ab373b724de)

**Comment by OStrama** [comment]
Do you have a temp sensor in your „Pufferspeicher“? I don‘t and so I see zero here, too. The question mark up to now is only used for entities we do not exactly know. When the meaning is confirmed we‘ll change the unit.
We try to filter out entities in the following way:
- when there is now answer from the modbus
- When the value is undefined regarding the documentation, i.e., temp value >32767 etc.

But some values are shown as a valid value of 0, even if there‘s no sensor behind it. I simply delete them in my dashboard.

**Comment by maddinhome** [comment]
I don't have a temp sensor in my "Pufferspeicher" for the heating. There is only an analog thermometer connected to the "Pufferspeicher". So ist ok if the value is zero.

`I simply delete them in my dashboard.` that's how I do it too now.  

Thank you again for your great work. I'm totally amazed by it.

This is a bit off topic and I hope it's not too rude for me to ask this: I'm trying with Smart Appliance Enabler 2.3.1
Read out the current power consumption of the heat pump and send it to the SMA portal of my photovoltaic system. I use register 36701 for this, but there is no value that SMA can process. Maybe you have another tip for me.

36701 is Integer an Input (FC=4) and have 1 Dataword (?)

**Comment by l3nkz** [comment]
This is the log from my system. Hope this helps

[debug_log_weishaupt_modbus.log](https://github.com/user-attachments/files/17780924/debug_log_weishaupt_modbus.log)

**Comment by OStrama** [comment]
@l3nkz it seems as your sensor „Luftansaugtemperatur“ is not available which leads to the crash of „Wärmeleistung“. Could you comment out the Line „Wärmeleistung“ in the ModbusItem list in hpconst.py?

**Comment by MadOne** [comment]
> This is a bit off topic and I hope it's not too rude for me to ask this: I'm trying with Smart Appliance Enabler 2.3.1\nRead out the current power consumption of the heat pump and send it to the SMA portal of my photovoltaic system. I use register 36701 for this, but there is no value that SMA can process. Maybe you have another tip for me.\n\n36701 is Integer an Input (FC=4) and have 1 Dataword (?)\n..and this is what comes out:\nMeter payload={\"energy\":0.08299998888888889,\"power\":9,\"time\":\"2024-11-15T19:59:27.360862986\",\"type\":\"MeterMessage\"}

No it is not rude. But i think you better ask the question at at the smart appliance enabler.  I have no clue what this is and cant test it. Anyways feel free to ask further questions.

**Comment by OStrama** [comment]
@maddinhome: The value you mentioned is an energy (kWh) value. Maybe, you‘d need a power (W) value for controlling your inverter? Since there‘s no direct power value on the modbus I installed a shelly 3 phase power meter that measures the complete power consumed by the heatpump including water pump, controller etc. Maybe, this would also be the easiest and most precise method for your application..

**Comment by OStrama** [comment]
Now I had some time to analyze the logs, thanks to everybody for providing them!
It seems that the availbale sensors differ from one heatpump model to the other. Here's the state of the three logs:
[Available Iterms.xlsx](https://github.com/user-attachments/files/17786743/Available.Iterms.xlsx)
I tested it with an unavailable entity for "Wärmeleistung" and I could reproduce the behavior that many entities are unavailable. 
In version 1.0.1 the follwoing is implemented:
- when "Luftansaugtemperatur is not available, use "Außentemperatur"
- if both are not available, Wärmeleistung will be None

**Comment by l3nkz** [comment]
Thanks for the fix! The values that were `unknown` are now available with this fix. However "Wärmeleistung" still does not seem to work for me. BTW I have a WGB and not a WBB heat pump. Maybe this is also the reason why I don't have a sensor for "Luftansaugtemperatur".

Another question, how did you create the Kennfeld files?

**Comment by OStrama** [comment]
You are welcome! Is Wärmeleistung available and wrong or unavailable?

An how-to for creating a power map file can be found here: https://github.com/OStrama/weishaupt_modbus/discussions/29#discussioncomment-11241297
If the values are wrong, an updated file could help..

**Comment by l3nkz** [comment]
It is still `unknown`. And I also didn't find anything in the debug log ...

**Comment by MadOne** [comment]
You have a "Sole" heatpump. So it is independent of the air temperature. Do you have wemportal? Do you see the incoming sole temperatur anywhere there or on the heatpump?

**Comment by OStrama** [comment]
Ahhh, thanks for checking! Yes, then the whole heat power calculation as implemented today makes no sense as it looks at the air temperature..
I think I first have to understand the diagrams in the manual of your HP ;-)
And of course sole temp. Would be required..

**Comment by l3nkz** [comment]
I can read out this value at the heatpump itself. Solevorlauf and Solerücklauf are available their. Does it make sense to ask Weishaupt for the corresponding Modbus registers? It seems as if WH is quite responsive in this regard.

**Comment by MadOne** [comment]
> I can see this value at the heatpump itself. Solevorlauf and Solerücklauf are available their. Does it make sense to ask Weishaupt for the corresponding Modbus registers? It seems as if WH is quite responsive in this regard.

Every help in identifying is appreciated. You could also check some registers in question with a python script / mobile app.
