### ISSUE TITLE
"Heizkennlinie" has wrong unit

### ISSUE THREAD

**Issue by backuprestore** [OStrama/weishaupt_modbus#36]
weishaupt_modbus V1.0

shouldn't that be unitless?

![grafik](https://github.com/user-attachments/assets/85bbbe9a-417f-4247-9601-ceec3c471ad4)

as allways... thanks for your work

**Comment by OStrama** [comment]
This should be an abbreviation for „Steigung“ ;-). What unit would you prefer? Perhaps none?

**Comment by backuprestore** [comment]
Ahhh ok… in my opinion, it’s unitless… , but now I know :-)
________________________________
Von: OStrama ***@***.***>
Gesendet: Friday, November 15, 2024 10:19:42 AM
An: OStrama/weishaupt_modbus ***@***.***>
Cc: backuprestore ***@***.***>; Author ***@***.***>
Betreff: Re: [OStrama/weishaupt_modbus] "Heizkennlinie" has wrong unit (Issue #36)


This should be an abbreviation for „Steigung“ ;-). What unit would you prefer? Perhaps none?

**Comment by OStrama** [comment]
Fixed in 1.0.1
