### ISSUE TITLE
WBB20 - Biblick20 - Kennfeld

### ISSUE THREAD

**Issue by backuprestore** [OStrama/weishaupt_modbus#37]
Interpolated outside of temperature range to meet -30 <-> 40 °C

{"known_x": [-30, -25, -20, -15, -10, -5, 0, 5, 10, 15, 20, 25, 30, 35, 40], "known_y": [[8399, 9402, 10605, 11963, 13431, 14964, 16517, 18045, 19503, 20846, 22029, 23007, 23735, 24168, 24261], [7749, 9221, 10851, 12571, 14313, 16010, 17595, 19000, 20157, 20999, 21459, 21469, 20961, 19868, 18123]], "known_t": [35, 55]}

**Comment by OStrama** [comment]
Thank you! Added the file to the repository..
