### ISSUE TITLE
Integration configuration fails 

### ISSUE THREAD

**Issue by Bertk** [OStrama/weishaupt_modbus#4]
**Describe the bug**
Configuration of integration fails with error:
<img width="472" alt="image" src="https://github.com/user-attachments/assets/e5b6af0e-2b7f-4ff3-a1e3-22a815f70174">

```
2024-10-11 09:09:57.961 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry 192.168.178.80 for weishaupt_wbb

  File "/config/custom_components/weishaupt_wbb/number.py", line 11, in <module>
    from .entities import BuildEntityList
  File "/config/custom_components/weishaupt_wbb/entities.py", line 12, in <module>
    from .kennfeld import PowerMap
  File "/config/custom_components/weishaupt_wbb/kennfeld.py", line 1, in <module>
    from scipy.interpolate import CubicSpline
ModuleNotFoundError: No module named 'scipy'
```

**To Reproduce**
1. Install weishaupt_wbb integration and start configuration
2. See error

**Expected behavior**
No error

**Home assistant device:**
 - Device: Home Assistant Yellow Kit
 - Core Version: 2024.10.1
 - OS: 13.1

**Additional context**
[Q: NumPy/SciPy and HASS.io](https://community.home-assistant.io/t/q-numpy-scipy-and-hass-io/150520)

There are also some additional messages for identities
<img width="433" alt="image" src="https://github.com/user-attachments/assets/806e1cec-9d0f-42c4-82df-c06276d64b9e">

**Comment by OStrama** [comment]
Please check out 0.0.2. I added scipy as requirement.

**Comment by OStrama** [comment]
Please check out 0.0.3. I added scipy as requirement. (in 0.0.2 code base was not yet synched..)

**Comment by Bertk** [comment]
Unfortunately this was not successful.

<img width="847" alt="image" src="https://github.com/user-attachments/assets/63df9f8b-346b-45a7-84e2-107bcd450449">

```
  File "/usr/src/homeassistant/homeassistant/requirements.py", line 170, in async_get_integration_with_requirements
    await future
  File "/usr/src/homeassistant/homeassistant/requirements.py", line 159, in async_get_integration_with_requirements
    await self._async_process_integration(integration, done)
  File "/usr/src/homeassistant/homeassistant/requirements.py", line 182, in _async_process_integration
    await self.async_process_requirements(
  File "/usr/src/homeassistant/homeassistant/requirements.py", line 269, in async_process_requirements
    await self._async_process_requirements(name, missing)
  File "/usr/src/homeassistant/homeassistant/requirements.py", line 307, in _async_process_requirements
    raise RequirementsNotFound(name, list(failures))
homeassistant.requirements.RequirementsNotFound: Requirements for weishaupt_wbb not found: ['scipy==1.14.1'].
```

**Comment by OStrama** [comment]
Ah, OK. I use core on a Pi 5. There adding the requirements solved the issue. 
I only use the cubic spline function from scipy..

do you have access to a terminal on HA yellow?

**Comment by Bertk** [comment]
Yes, I have access to a terminal.

**Comment by OStrama** [comment]
Can you try to enter:
python -m pip install scipy
Or even with sudo, when no rights to install..

**Comment by OStrama** [comment]
when installing scipy, can you tell me the version that was installed?

**Comment by Bertk** [comment]
I used `apk add py3-scipy`. See screenshot.
<img width="1013" alt="image" src="https://github.com/user-attachments/assets/7be1dff5-2460-4115-b077-dc3227db8289">

```
(19/20) Installing py3-scipy (1.11.4-r2)
(20/20) Installing py3-scipy-pyc (1.11.4-r2)
```

**Comment by OStrama** [comment]
OK, that's too much for me as newbie ;-)
Please check out v 0.0.4. I removed scipy temporary. Will find another interpolation method..

**Comment by Bertk** [comment]
OK. This one was successful. :+1

<img width="1061" alt="image" src="https://github.com/user-attachments/assets/58d2ac98-bb66-4665-9efc-38c5878a78fe">

Some values are strange …

<img width="356" alt="image" src="https://github.com/user-attachments/assets/97843703-515b-4e5b-8ff8-7bb749c184f6">

<img width="371" alt="image" src="https://github.com/user-attachments/assets/b1967f04-1da0-4747-be7e-cce74ef89b64">

<img width="370" alt="image" src="https://github.com/user-attachments/assets/2f26d696-2519-407c-9864-22e4622ff7cd">

**Comment by OStrama** [comment]
Thanks for the info! The strange values seem to be not available at your heatpump. Do you have configured a 2nd heater (i.e. a gas heater) that takes over at Bivalenztemp?
However, a not available value should be +/- 32768 according to the documentation?

**Comment by Bertk** [comment]
I see. I do not have a 2nd heater. I will rearrange the cards tomorrow and remove it.
Maybe this could be avoided by the configuration dialog.

**Comment by Bertk** [comment]
Some entities do not have a valid unit_of_measurement. Also state_class is missing with the new Integration.

- sensor.warmepumpe_solltemperatur => should be °C
- wärmepumpe-drehzahl_pumpe_m1 => should be %

<img width="703" alt="image" src="https://github.com/user-attachments/assets/63b7e27f-ca38-4cc8-b756-a042ff844dcf">

name typo: warmwassertemepratur => **warmwassertemperatur**

**Comment by OStrama** [comment]
I‘m afraid they do not belong to the integration „weishaupt_wbb“
Please have a look at the file hpconst.py. There‘s a structure at the end where you can see all names provided by my integration.
(Some entities do not have a state class, I‘ll correct this..)

**Comment by Bertk** [comment]
Thank you for the hint. This is a mix-up of entities of _Weishaupt WEM Portal_ and _Weishaupt weishaupt_modbus_ integration. I will remove _Weishaupt WEM Portal_ integration as soon as a first release of **weishaupt_wbb** is available :smile:

The naming of the entities could be improved and I wonder what will happen if 2 weishaupt heat pumps will be configured 😉 .

https://github.com/OStrama/weishaupt_modbus/blob/76da2dc50c8d578ddc0f6d381a4df46f92676f7b/custom_components/weishaupt_modbus/hpconst.py#L355

**Comment by OStrama** [comment]
Yes, there are some enhancements necessary and I‘m still learning a lot about Python and home assistant integrations. For example, how to manage additional parameters at setup, translations, …

How likely will it happen that there‘s a config with two heat pumps in one home assistant instance? Do users have one HA instance to manage several homes?

**Comment by Bertk** [comment]
I do not know a real example but someone could have installed a heat pump for warm water only and will later exchange fossil heating with another heat pump. This might be a scenario for the near future.

**Comment by Bertk** [comment]
Thank you for the this great Weishaupt modbus integration.

<img width="329" alt="image" src="https://github.com/user-attachments/assets/a54b7fa7-94ef-46b6-aad8-fbfd36c755d3">

<img width="335" alt="image" src="https://github.com/user-attachments/assets/1ca2bd1f-431f-4e9c-bb30-7a0929c5378c">
