### ISSUE TITLE
Weishaupt Gas Heating support

### ISSUE THREAD

**Issue by dm82m** [OStrama/weishaupt_modbus#43]
**Is your feature request related to a problem? Please describe.**
Hey guys,
we were previously using a integration (https://github.com/erikkastelec/hass-WEM-Portal) that needs a wemportal.com paid account and then scrapes the heating data from the web portal aswell as the mobile api endpoint for the app. It worked well couple of years but now Weishaupt secured it more and is forbidding the automated data requests.

One user tested your integration and I did aswell. Even that we DO NOT HAVE bought the modbus module from Weishaupt it even works - at least half the way. So we can install the integration, it seems also to connect and shows several entities but they do not have a values.

**Describe the solution you'd like**
It would be more than great, if you could try make the Weishaupt gas heaters also supported by your integration. If you would need local network access to the device or some modbus queries to be executed, just drop me a message.

**Describe alternatives you've considered**
Sadly there is no alternative at the moment. So we are getting no data anymore with the old integration, there is no real solution in sight.

**Additional context**
<img width="1455" alt="image" src="https://github.com/user-attachments/assets/f6c276a2-e5d0-460c-bef8-80ebb3f6cfb5">

**Comment by dm82m** [comment]
I did a bit more debugging and think, that your integration is not really checking for an existing endpoint. it just creates the entities and due to a missing endpoint they have no data.

cause if I use mbpoll to query the gas heating, I get no connection:

```
dirk.maucher@MAC-JY9QJFH75M ~ % mbpoll -m tcp -a 0 -r 100 -c 10 192.168.178.31
mbpoll 1.0-0 - ModBus(R) Master Simulator
Copyright (c) 2015-2023 Pascal JEAN, https://github.com/epsilonrt/mbpoll
This program comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it
under certain conditions; type 'mbpoll -w' for details.

mbpoll: Connection failed: Connection refused.
```

**Comment by MadOne** [comment]
Well thats interesting. Our integration checks for Connection and retrys 2 times. You should see Connection failed in the logs. Can you run this python script?
https://github.com/OStrama/weishaupt_modbus/blob/main/custom_components%2Fweishaupt_modbus%2Ftest_modbus.py

**Comment by dm82m** [comment]
how can I run the script within home assistant? tried to directly execute it on HA shell but throws me this:

```
➜  weishaupt_modbus git:(master) ✗ python test_modbus.py 
Traceback (most recent call last):
  File "/homeassistant/custom_components/weishaupt_modbus/test_modbus.py", line 1, in <module>
    import asyncio
  File "/usr/lib/python3.12/asyncio/__init__.py", line 8, in <module>
    from .base_events import *
  File "/usr/lib/python3.12/asyncio/base_events.py", line 24, in <module>
    import socket
  File "/usr/lib/python3.12/socket.py", line 55, in <module>
    import os, sys, io, selectors
  File "/usr/lib/python3.12/selectors.py", line 12, in <module>
    import select
  File "/homeassistant/custom_components/weishaupt_modbus/select.py", line 3, in <module>
    from homeassistant.config_entries import ConfigEntry
ModuleNotFoundError: No module named 'homeassistant'
```

**Comment by MadOne** [comment]
You need to run it locally

**Comment by dm82m** [comment]
locally on the 'homeassistant' container I get this:

```
Traceback (most recent call last):
  File "/config/custom_components/weishaupt_modbus/test_modbus.py", line 1, in <module>
    import asyncio
  File "/usr/local/lib/python3.12/asyncio/__init__.py", line 8, in <module>
    from .base_events import *
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 24, in <module>
    import socket
  File "/usr/local/lib/python3.12/socket.py", line 55, in <module>
    import os, sys, io, selectors
  File "/usr/local/lib/python3.12/selectors.py", line 12, in <module>
    import select
  File "/config/custom_components/weishaupt_modbus/select.py", line 3, in <module>
    from homeassistant.config_entries import ConfigEntry
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 32, in <module>
    from . import data_entry_flow, loader
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 21, in <module>
    from .core import HomeAssistant, callback
  File "/usr/src/homeassistant/homeassistant/core.py", line 96, in <module>
    from .util.async_ import (
  File "/usr/src/homeassistant/homeassistant/util/async_.py", line 5, in <module>
    from asyncio import (
ImportError: cannot import name 'AbstractEventLoop' from partially initialized module 'asyncio' (most likely due to a circular import) (/usr/local/lib/python3.12/asyncio/__init__.py)
```

**Comment by MadOne** [comment]
I ran it on my pc locally. Did not run in the ha Environment.

**Comment by dm82m** [comment]
okay, created a venv on my mac, installed pymodbus and started the script:

```
(test) dirk.maucher@MAC-JY9QJFH75M test % python test_modbus.py
/Users/dirk.maucher/Downloads/test/test_modbus.py:110: DeprecationWarning: There is no current event loop
  loop = asyncio.get_event_loop()
2024-11-17 12:09:31,908 DEBUG base:64 Connecting to 192.168.42.144:502.
2024-11-17 12:09:31,908 DEBUG transport:236 Connecting comm
2024-11-17 12:09:34,910 WARNING transport:244 Failed to connect
Traceback (most recent call last):
  File "/Users/dirk.maucher/Downloads/test/test_modbus.py", line 111, in <module>
    loop.run_until_complete(main())
    ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.13/3.13.0_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/asyncio/base_events.py", line 721, in run_until_complete
    return future.result()
           ~~~~~~~~~~~~~^^
  File "/Users/dirk.maucher/Downloads/test/test_modbus.py", line 72, in main
    if rr.isError():
       ^^
UnboundLocalError: cannot access local variable 'rr' where it is not associated with a value
```

**Comment by dm82m** [comment]
would say that my initial assumption was correct -> weishaupt device is not responding on port 502 - so no modbus tcp running!?

**Comment by MadOne** [comment]
At least there is no response. On the the heatpumps you have to enable Modus and whitelist ip / net for access. Maybe you have such an option? Some heatpumps have a local http server and a web frontend. Do you have something like this. 

Fir enableing the webserver i needed the oem menu (code 21)

**Comment by MrAhmalo** [comment]
There is only a JSON Interface on the Weishaupt Heaters. Sadly no Modbus option in the settings.

**Comment by MadOne** [comment]
Perhaps we could implement the json reading. Can you perhaps share such a json?

**Comment by dm82m** [comment]
@MrAhmalo I enabled the json interface on my gas heating system. but I cant access it, so its not answering on all the ports I tested. the manual tells something like it should be accessible on port 80 an user/password is admin/Admin123 - have you had any success receiving json data?

**Comment by MrAhmalo** [comment]
@dm82m I got some interesting news. I was not able to access the JSON interface while the Heater is connected to my router.
But connecting my PC via a LAN Cable directly to the heater worked. First, I did not know the new IP Address of the Heater, but http://wem-sg worked. There I saw just a simple network settings page for the heater. But using my browsers developer network inspection menu, I noticed, that the webpage accessed some JSON Endpoints.

Webpage:
![grafik](https://github.com/user-attachments/assets/bcc238cf-f02e-44ea-b83a-a8343002b5e6)

JSON Endpoints:
![grafik](https://github.com/user-attachments/assets/0bed1f75-8365-4201-9dc0-7b8d3914251e)

Most of them were just some scripts for the webpage functionality, I think.
But there was also a JSON Endpoint. (http://wem-sg/ajax/CanApiJson.json)

I was able to log in and get data via a python script, but it only responded with unreadable information.
From what I understand, this JSON Endpoint is also only for the webpage functionality, but I might be wrong.

I just hope that there is some way to access the system by it.

Here is the python script I made:
python`import requests

# JSON URL
url = "http://wem-sg/ajax/CanApiJson.json"

# Login Data
username = "admin"
password = "Admin123"

response = requests.get(url, auth=(username, password))

data = response.json()

if response.status_code == 200:
    print(response.json())
else:
    print(f"Error: {response.status_code}")
`

**Comment by dm82m** [comment]
What answer do you get?

**Comment by MadOne** [comment]
I don't even get a connection. But i can login via browser:
![image](https://github.com/user-attachments/assets/269166a1-cb57-4ad8-a79a-1e1a2de084ce)

But with the following script i get an 404
```
import requests
# JSON URL
url = "http://10.10.1.225/ajax/CanApiJson.json"
# Login Data
username = "admin"
password = "Admin123"
response = requests.get(url, auth=(username, password))
print(response)
```

<Response [404]>

**Comment by MrAhmalo** [comment]
@MadOne How could you log in and get this data page?

**Comment by MadOne** [comment]
I just open the ip in browser. (I am on an wbb heatpump)

**Comment by MrAhmalo** [comment]
Yeah the heaters are very different there

**Comment by developer-stephan** [comment]
> {"ID":"00000003","SRC":"SYS","CAPI":{"NN":6,"N01":{"VG":"020600250c01000100"},"N02":{"VG":"020600250c02000123"},"N03":{"VG":"020600250c0300017e"},"N04":{"VG":"020600250c040001ce"},"N05":{"VG":"020600250c05000159"},"N06":{"VG":"020600250c060001c1"}}}

![grafik](https://github.com/user-attachments/assets/f1873f95-82e9-4ede-888c-dcef4be3a321)

Interessante Ideen von ChatGPT

**Comment by MadOne** [comment]
Schaut mal hier:
https://github.com/lairsdragon/nodered-weishaupt

**Comment by OStrama** [comment]
Yes, looks interesting. But do you think it would make sense to put this all in one integration?

**Comment by MadOne** [comment]
Yes i think so. There are so much possible sources (modbus, local webserver, json) and some devices share a subset of these. But not all sources deliver all information.
For example modbus can not display the firmware version, the local webserver does.
Some information on modbus are not correct (2.wez , IO,)

We for example could use modbus and some values of the webserver that we cant get from modbus. Modbus is fast and relieable, so a good choice for sensors. But now and then we could scrape the webserver for missing values.

The models without modbus could only use the local web scraping,

And we should not let down the guys with just a json response.

**Comment by OStrama** [comment]
OK, then it would make sense to enhance the class structure in a way that these other sources can be added conveniently via the item lists. Will be interesting ;-)

**Comment by MadOne** [comment]
I was thinking about making api_items additional to the Modbus_Items. The problem i see, is the update coordinator. We cant hammer the internal web server with so much requests as we can with modbus. I have to wait 10 sec between requests to get reliable responses. I think the best would be a second coordinator but im unsure if this is possible.

**Comment by OStrama** [comment]
We already have a few of them. For every device and I think sensor class a new one is created..

**Comment by OStrama** [comment]
I think the polling interval for the modbus items is 30 sec. 
For the api calls we should be able to do one call only for many entities..

**Comment by MadOne** [comment]
@OStrama Ah i see. Every platform creates its own coordinator. So we could easily create a coordinator for the api fetches.

@MrAhmalo Did you create a username and log in? I think this was the page i got before i created an account.

**Comment by MadOne** [comment]
Original request is impossible due to no modbus on device.
We will integrate the WebInterface provided by multiple devices.

If you have further information on pure json responses and want us to integreate feel free to open a new feature request.

**Comment by BorgNumberOne** [comment]
If someone is interested in the Weishaupt JSON protocol (for using it in Node Red or Home Assistant or iobroker etc.):
https://github.com/BorgNumberOne/Weishaupt_CanApiJson/

If some one is interested in: doing tests / experiments with the Weishaupt JSON protocol, I have got the Weishaupt Gateway WEM-Modbus converter. :) it works perfectly together with modbustester / modbusmaster.
