### ISSUE TITLE
Why are the entities renamed in version 1.02?

### ISSUE THREAD

**Issue by maddinhome** [OStrama/weishaupt_modbus#48]
**Describe the bug**
I updated to 1.02 and my entities were no longer there, only two new ones "dev_heizkreis_Zuhause" and "dev_warmwasser_Zuhause". All other entities were no longer present, only the groups such as "Eingänge/Ausgänge_Zuhause" but no entities. After deleting and reconfiguring, only new entity groups with dev_.... remained. Unfortunately, the entities were also renamed. Now there is no more automation and no dashboard working. 

I'm now back to version 1.01 with a backup.

**Screenshots**
![Screenshot 2024-11-22 082559](https://github.com/user-attachments/assets/492a2013-961d-4c78-b82f-3a8d743f2bb6)

**Comment by MadOne** [comment]
After initialisation the entitys need some time. Did you refresh (F5)?

**Comment by maddinhome** [comment]
No, I didn't change anything, I just did an update and after the entities in the previous overview disappeared, I reconfigured them and did the same as before. With devicepostfix “Zuhause" and the json map that is right for me. (WSB8)

**Comment by maddinhome** [comment]
Ok, I'll try again... I have a backup.

**Comment by MadOne** [comment]
When you edit the postfix you get new devices and entitys. You should remove it. There was a problem with the translation feature whitch might affect you. Please remove the integration through hacs and install it freshly. (Without postfix)

**Comment by maddinhome** [comment]
I'm currently reinstalling... and will upload a few pictures soon.

**Comment by MadOne** [comment]
Backup should also work. But dont use a device postfix if you previously did not

**Comment by maddinhome** [comment]
I did use it before....: "Zuhause". 

I only did an update and didn't change any configuration and unfortunately there are new groups - 14 instead of 7 - and there are no longer any entities in my "old" groups.


![Screenshot 2024-11-22 083904](https://github.com/user-attachments/assets/9ec0017a-9e9d-4d2a-8232-105b55535182)
![Screenshot 2024-11-22 083952](https://github.com/user-attachments/assets/0d8dfdcd-ff0b-4705-a2be-93f58499e192)
![Screenshot 2024-11-22 084207](https://github.com/user-attachments/assets/e0f6b213-5da3-4e4c-8da8-dbf78ff04aa4)
![Screenshot 2024-11-22 084754](https://github.com/user-attachments/assets/0fb7b1f2-bc82-4876-99e4-120160fe43d7)

**Comment by MadOne** [comment]
Please try the pre release: 1.0.3_pre.
You will get no update alert. You have to select it manually.

**Comment by maddinhome** [comment]
ok I try it.... thank you

**Comment by maddinhome** [comment]
It worked. Thank you for the quick response. You are really great.

**Comment by MadOne** [comment]
You are welcome. I will push this pre as full release. Sorry for breaking things.
