### ISSUE TITLE
please add a dashboard yaml

### ISSUE THREAD

**Issue by cobordism** [OStrama/weishaupt_modbus#5]
Hello,
Thank you for your efforts. I have been futzing with my heatpump for ages and finally I have most of the modbus protocol working thanks to your integration.

I'd like to ask for two features.

1. Can you rename the entities from things like `sensor.betrieb` to maybe `sensor.wwp_betrieb`? Otherwise it becomes harder to keep track of which entity belongs to the heatpump.

2. It looks like you've got a cool dashboard of all the WWP features. Can you include the yaml in the repo, or otherwise share it with us? 

thank you

**Comment by OStrama** [comment]
Thanks! 
I added a dashboard.yaml file to the repository. However, it also contains other entities like my shelly watt meter that measures the electric energy consumption of the heat pump.
Regarding the names I‘ll try to put the config in a yaml file, too. Meanwhile you could simply edit the names of all entities in the hpconst.py file 😏

**Comment by MadOne** [comment]
@OStrama : I suggest to introduce a prefix during setup. This would also allow multiple heatpumps.

**Comment by OStrama** [comment]
Good Idea! Do you know how to build the data structure for the setup panel?

**Comment by MadOne** [comment]
Not yet. I just copied an example and changed the bare minumum. But with a bit of research this should be doable

**Comment by OStrama** [comment]
There are two parameters available now:

Prefix: Mainly to migrate from MadOne‘s integration
Device Postfix: to distinguish between different devices in the HA GUI, see readme.

Enhancement to add multiple heatpumps is resolved in 0.0.8.pre7 and will be integrated in 0.0.8

**Comment by MadOne** [comment]
Do we really add different devices? I think we add a new device and overwrite the values of the old one.

When we have more devices we need to create entitiys for both devices.

**Comment by OStrama** [comment]
Yes, when we only have one heatpump this is true. 
One request above was for adding a second heatpump. If I only change the prefix, I get something like this:

![image](https://github.com/user-attachments/assets/6ec277f2-7689-45c1-9f7d-3f158d7ed543)

When using the postfix, too, it looks like this:

![image](https://github.com/user-attachments/assets/1fe81bcc-8d75-499c-9c4a-27a47b092959)

and 

![image](https://github.com/user-attachments/assets/7579f5d7-cb14-4326-83bc-d5f6cb331503)

**Comment by MadOne** [comment]
Im glad i was wrong. Im really impressed by your buildings ;).
