### ISSUE TITLE
Min value for number.warmwasser_normal and number.warmwasser_absenk

### ISSUE THREAD

**Issue by exp1338** [OStrama/weishaupt_modbus#54]
**Is your feature request related to a problem? Please describe.**
If we on vacation i try to decrease the target temperature to 20 or 21°C

**Describe the solution you'd like**
Please allow to decrease the target temperatures below 30°C. I like to see 20°C. After setting to 20° the heatpump avoid to heat up water stoarge. If we not at home its not useful to heat it up to 30°.

**Describe alternatives you've considered**
.....

**Additional context**
I hope it is possible

**Comment by exp1338** [comment]
Thanks, after a restart of HA it works fine, :) Will be create if you can adjust the min value in one of the next releases. 👍

**Comment by OStrama** [comment]
Temperature ranges now are aligned with WEM portal in Version 1.0.4
We allow the same range as WEM portal. (Values outside these ranges will not be accepted by the heat pump..)

**Comment by exp1338** [comment]
Perfect Thanks.
