### ISSUE TITLE
Typo in sensor name hpconst.py: "Warmwassertemepratur"

### ISSUE THREAD

**Issue by Bertk** [OStrama/weishaupt_modbus#6]
Typo in sensor name hpconst.py line 355
https://github.com/OStrama/weishaupt_modbus/blob/76da2dc50c8d578ddc0f6d381a4df46f92676f7b/custom_components/weishaupt_modbus/hpconst.py#L355

Please correct spelling: "Warmwassertemperatur"

**Comment by OStrama** [comment]
fixed in 0.0.6 ;-)
