### ISSUE TITLE
Statistic entities for "Abtauen" energy are not correct

### ISSUE THREAD

**Issue by Bertk** [OStrama/weishaupt_modbus#70]
**Describe the bug**
Statistic entities values are always "0" but monthly entity has values.

- sensor.wh_statistik_abtauen_energie_gestern
- sensor.wh_statistik_abtauen_energie_heute

`sensor.wh_statistik_abtauen_energie_monat` does not represent actual value and occurrence.

**To Reproduce**
Check statistic entities for "abtauen energy".

**Expected behavior**
`sensor.wh_statistik_abtauen_energie_gestern` and `sensor.wh_statistik_abtauen_energie_heute` show actual values.

**Screenshots**
<img width="584" alt="image" src="https://github.com/user-attachments/assets/ec580115-0a19-46dc-a04c-c724435b8e89">

![image](https://github.com/user-attachments/assets/84ef583e-1f01-43d2-a28d-221e1be30561)

**Comment by MadOne** [comment]
The heatpump always floors the values (0.99 = 0). So if the daily consumption for abtauen is below 1kw/h it will be displayed as 0. Sadly there is nothing we could do about that.

Please confirm this is the case so i can close this issue.

**Comment by Bertk** [comment]
Thank you for the information. The daily statistic should have at least 1-digit decimals for kWh dimension.

Yes, I also observed now an update of "Abtauen Energie heute".
<img width="344" alt="image" src="https://github.com/user-attachments/assets/5cac0cc9-52b5-4c82-bbe0-367bf81e7d86">

**Comment by MadOne** [comment]
I agree that there should be at least 1 decimal digit. But we can only work with the rounded integer values Weishaupt provides. 

Closed.
