### ISSUE TITLE
Precision for kWh statistic values should be improved

### ISSUE THREAD

**Issue by Bertk** [OStrama/weishaupt_modbus#76]
**Describe the bug**
Sensor value `sensor.wh_statistik_elektr_energie_heute` uses rounded number for kWh but should use a 3-digit precision.

=> Energy dashboard has incorrect graphs.

**To Reproduce**
Compare specific statistic sensor values from weishaupt modbus integration with weishaupt web portal.

**Expected behavior**
Should have identical values for same sensor (see screen shots) 

**Screenshots**
WEM portal has statistic kWh value with 3-digit precision
![image](https://github.com/user-attachments/assets/3f120cc9-ec84-4a0f-a70e-dbc5b69d6da7)

The energie dash board show irritating values
![image](https://github.com/user-attachments/assets/c05e1e0d-a54a-4002-92fa-57f23cb2dfe1)

**Additional context**

**Comment by Bertk** [comment]
see also:

https://community.home-assistant.io/t/weishaupt-heatpump-integration-via-modbus/436823/19

<img width="684" alt="image" src="https://github.com/user-attachments/assets/a1b77dbd-d740-4d8f-8fe5-4f8b82f238c7">

**Comment by MadOne** [comment]
Just like with "Abtauen" we only get Integer values from Mobus. Again Weishaupt floors the values (0.99 = 0).

I am not sure if you understand that we only read values from modbus that weishaupt publishes to us. We can only read and write vales weishaupt allows us. We are not related to weishaupt in any manner.

**Comment by MadOne** [comment]
Oh i was actually wrong. In this case weishaupt seems to correctly round (up).

We have no influence on what values weishaupt provides to us ==> Closed.

**Comment by Bertk** [comment]
I am not sure. I noticed the rounding starts with >= 0,5. In my understanding this does not fit with the "0,99 = 0" explanation. 

![image](https://github.com/user-attachments/assets/4b091395-d033-4c75-9e11-bfc8cf45f0c1)

**Comment by Bertk** [comment]
I will use the Weishaupt API statistic sensor values for the energy dashboard which will show accurate power consumption.

<img width="500" alt="image" src="https://github.com/user-attachments/assets/e2233ee3-17b3-4853-a501-8f1ba8806329">

**Comment by MadOne** [comment]
As i wrote. In this case they seem to correctly round 
>=0.5 = up
<0.5 = down.
This is not always the case.

Anyways this does not matter at all. We have to take the values we got from weishaupt.

**Comment by MadOne** [comment]
> I will use the Weishaupt API statistic sensor values for the energy dashboard which will show accurate power consumption.
> 
> <img alt="image" width="500" src="https://private-user-images.githubusercontent.com/2315215/393585726-e2233ee3-17b3-4853-a501-8f1ba8806329.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM2NTI4MzQsIm5iZiI6MTczMzY1MjUzNCwicGF0aCI6Ii8yMzE1MjE1LzM5MzU4NTcyNi1lMjIzM2VlMy0xN2IzLTQ4NTMtYTUwMS04ZjFiYTg4MDYzMjkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMDhUMTAwODU0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDA4ZmQ5ODRkNThjOTFjZmNmOWY2MTI5NWNjODAwMjg0MDQyMmFhNmQ3OTBiNDU2YWM1ODllOTQ5NjMwYWE1MyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.-Fp4KdcWsIn5iYI2ZeNANVpLhct4xO7-xAbDybuFJMA">

What you mean with weishaupt api? WEM Portal?

**Comment by Bertk** [comment]
YES. WEM Portal integration.

**Comment by MadOne** [comment]
This is your best bet for now. 
We are currently working on integrating the local WebInterface. This one provides three digits accuracy.

**Comment by MadOne** [comment]
Little teaser:
![Bildschirmfoto vom 2024-12-08 11-24-52](https://github.com/user-attachments/assets/fdb2db40-41a1-469b-b54d-a910046d63a3)

**Comment by Bertk** [comment]
Looks good.

There is a lot of register space in this register table. My former team typically introduced always new "register" after the existing ones for backward compatibility reason whenever a data type update was required (very rare scenario but it happend).

**Comment by MadOne** [comment]
I am not sure what you want to tell me. You are / were working for weishaupt?

**Comment by Bertk** [comment]
No, I was not working for Weishaupt but for a company which build and ships medical imaging devices.

**Comment by Bertk** [comment]
I wonder how this is done with **Weishaupt WEM Portal**

![Image](https://github.com/user-attachments/assets/92263eb0-472b-4ff0-b188-eb5b064a1179)

**Comment by MadOne** [comment]
Because they dont use modbus and can use the unrounded values.

**Comment by MadOne** [comment]
We used different versions of [this](https://github.com/OStrama/weishaupt_modbus/blob/main/custom_components/weishaupt_modbus/test_modbus.py) script to scan all possible modbus values for response and put them together. Then we added the known register info from the weishaupt documentation. 

This was used to check for missing information / errors of weishaupt documentation.
