### ISSUE TITLE
Add support for Heizkries 2+

### ISSUE THREAD

**Issue by eddiewardoo** [OStrama/weishaupt_modbus#8]
![image](https://github.com/user-attachments/assets/f06a023d-f12e-430f-9be8-0301fbface20)

The doc shows the IDs for muliple Heizkris. I myself have 2. The first one works from the current version. Just need the second. Perhaps others have more (upto 5 is possible it seams)

BTW great work!

**Comment by OStrama** [comment]
Thanks for the hint! It should be easily possible to do this by copying and modifying the corresponding lines in hpconst.py. Could you add the lines and test it, since I only have one?

**Comment by eddiewardoo** [comment]
Will do. Already made the edit yesterday on my hpconst.py but did not work will check this tomorrow when I find time. Likely have to reinstall again. 

To confirm what needs to be edited:
Devices needs to be edited to add the new HZ

```
class DeviceConstants:
    SYS = "System"
    WP = "Wärmepumpe"
    WW = "Warmwasser"
    HZ1 = "Heizkreis 1"
    HZ2 = "Heizkreis 2"
    W2 = "2. Wärmeerzeuger"
    ST = "Statistik"
```

And MODBUS_SYS_ITEMS needs to be edited (HZ1) and HZ2 added with the new IDs. 
```
MODBUS_SYS_ITEMS = [
...
    ModbusItem(31101,"Raumsolltemperatur",FORMATS.TEMPERATUR,TYPES.SENSOR,DEVICES.HZ1, TEMPRANGE_ROOM),
    ModbusItem(31102,"Raumtemperatur",FORMATS.TEMPERATUR,TYPES.SENSOR,DEVICES.HZ1, TEMPRANGE_ROOM),
    ModbusItem(31103,"Raumfeuchte",FORMATS.PERCENTAGE,TYPES.SENSOR,DEVICES.HZ1),
    ModbusItem(31104,"Vorlaufsolltemperatur",FORMATS.TEMPERATUR,TYPES.SENSOR,DEVICES.HZ1, TEMPRANGE_STD),
    ModbusItem(31105,"HZ_Vorlauftemperatur",FORMATS.TEMPERATUR,TYPES.SENSOR,DEVICES.HZ1, TEMPRANGE_STD),
    ModbusItem(41101,"HZ_Konfiguration",FORMATS.STATUS,TYPES.NUMBER_RO,DEVICES.HZ1, HZ_KONFIGURATION),
    ModbusItem(41102,"Anforderung Typ",FORMATS.STATUS,TYPES.NUMBER_RO,DEVICES.HZ1, HZ_ANFORDERUNG),
    ModbusItem(41103,"Betriebsart",FORMATS.STATUS,TYPES.SELECT,DEVICES.HZ1, HZ_BETRIEBSART),
    ModbusItem(41104,"Pause / Party",FORMATS.STATUS,TYPES.SELECT,DEVICES.HZ1, HZ_PARTY_PAUSE),
    ModbusItem(41105,"Raumsolltemperatur Komfort",FORMATS.TEMPERATUR,TYPES.NUMBER,DEVICES.HZ1,TEMPRANGE_ROOM),
    ModbusItem(41106,"Raumsolltemperatur Normal",FORMATS.TEMPERATUR,TYPES.NUMBER,DEVICES.HZ1,TEMPRANGE_ROOM),
    ModbusItem(41107,"Raumsolltemperatur Absenk",FORMATS.TEMPERATUR,TYPES.NUMBER,DEVICES.HZ1,TEMPRANGE_ROOM),
    ModbusItem(41108,"Heizkennlinie",FORMATS.KENNLINIE,TYPES.NUMBER,DEVICES.HZ1,RANGE_HZKENNLINIE),
    ModbusItem(41109,"Sommer Winter Umschaltung",FORMATS.TEMPERATUR,TYPES.NUMBER,DEVICES.HZ1,TEMPRANGE_ROOM),
    ModbusItem(41110,"Heizen Konstanttemperatur",FORMATS.TEMPERATUR,TYPES.NUMBER_RO,DEVICES.HZ1,TEMPRANGE_ROOM),
    ModbusItem(41111,"Heizen Konstanttemp Absenk",FORMATS.TEMPERATUR,TYPES.NUMBER_RO,DEVICES.HZ1,TEMPRANGE_ROOM),
    ModbusItem(41112,"Kühlen Konstanttemperatur",FORMATS.TEMPERATUR,TYPES.NUMBER_RO,DEVICES.HZ1,TEMPRANGE_ROOM),

    ModbusItem(31201,"Raumsolltemperatur",FORMATS.TEMPERATUR,TYPES.SENSOR,DEVICES.HZ2, TEMPRANGE_ROOM),
    ModbusItem(31202,"Raumtemperatur",FORMATS.TEMPERATUR,TYPES.SENSOR,DEVICES.HZ2, TEMPRANGE_ROOM),
    ModbusItem(31203,"Raumfeuchte",FORMATS.PERCENTAGE,TYPES.SENSOR,DEVICES.HZ2),
    ModbusItem(31204,"Vorlaufsolltemperatur",FORMATS.TEMPERATUR,TYPES.SENSOR,DEVICES.HZ2, TEMPRANGE_STD),
    ModbusItem(31205,"HZ_Vorlauftemperatur",FORMATS.TEMPERATUR,TYPES.SENSOR,DEVICES.HZ2, TEMPRANGE_STD),
    ModbusItem(41201,"HZ_Konfiguration",FORMATS.STATUS,TYPES.NUMBER_RO,DEVICES.HZ2, HZ_KONFIGURATION),
    ModbusItem(41202,"Anforderung Typ",FORMATS.STATUS,TYPES.NUMBER_RO,DEVICES.HZ2, HZ_ANFORDERUNG),
    ModbusItem(41203,"Betriebsart",FORMATS.STATUS,TYPES.SELECT,DEVICES.HZ2, HZ_BETRIEBSART),
    ModbusItem(41204,"Pause / Party",FORMATS.STATUS,TYPES.SELECT,DEVICES.HZ2, HZ_PARTY_PAUSE),
    ModbusItem(41205,"Raumsolltemperatur Komfort",FORMATS.TEMPERATUR,TYPES.NUMBER,DEVICES.HZ2,TEMPRANGE_ROOM),
    ModbusItem(41206,"Raumsolltemperatur Normal",FORMATS.TEMPERATUR,TYPES.NUMBER,DEVICES.HZ2,TEMPRANGE_ROOM),
    ModbusItem(41207,"Raumsolltemperatur Absenk",FORMATS.TEMPERATUR,TYPES.NUMBER,DEVICES.HZ2,TEMPRANGE_ROOM),
    ModbusItem(41208,"Heizkennlinie",FORMATS.KENNLINIE,TYPES.NUMBER,DEVICES.HZ2,RANGE_HZKENNLINIE),
    ModbusItem(41209,"Sommer Winter Umschaltung",FORMATS.TEMPERATUR,TYPES.NUMBER,DEVICES.HZ2,TEMPRANGE_ROOM),
    ModbusItem(41210,"Heizen Konstanttemperatur",FORMATS.TEMPERATUR,TYPES.NUMBER_RO,DEVICES.HZ2,TEMPRANGE_ROOM),
    ModbusItem(41211,"Heizen Konstanttemp Absenk",FORMATS.TEMPERATUR,TYPES.NUMBER_RO,DEVICES.HZ2,TEMPRANGE_ROOM),
    ModbusItem(41212,"Kühlen Konstanttemperatur",FORMATS.TEMPERATUR,TYPES.NUMBER_RO,DEVICES.HZ2,TEMPRANGE_ROOM),
...
```
Any other thing I missed?

**Comment by OStrama** [comment]
I see the issue: The names of different entities are the same, so you‘ll also see errors in the log, I guess.
The Names of the entities should be different, also if they belong to different devices..

**Comment by MadOne** [comment]
What about adding ALL possible ModbusItems.
Before creating the entitys check if they are responding, if not remove them from the list.

This would solve the problem of "Raumtemperatur, Raumfeuchte, HZ_Vorlauftemperatur....) witch most users wont have.

**Comment by OStrama** [comment]
> What about adding ALL possible ModbusItems. Before creating the entitys check if they are responding, if not remove them from the list.
> 
> This would solve the problem of "Raumtemperatur, Raumfeuchte, HZ_Vorlauftemperatur....) witch most users wont have.

Yes, when the async reading is stable we should do this. Maybe when building (BuildEntityList) the list try to read it and if not accessible discard it..

**Comment by MadOne** [comment]
![image](https://github.com/user-attachments/assets/e4a7d71b-b80c-4754-b557-e9722cc192c8)

This looks weerd.
There can't be any Raumtemperatur2 or Raumfeuchte2.
Raumsolltemperatur2 should be either 21°C(Komfort) or 20°C(Normal) or 18°C(Absenk) as the sliders show.

**Comment by MadOne** [comment]
WEM Portal only gives me 1 Heiskreis.
![image](https://github.com/user-attachments/assets/bd017d48-93ea-4dde-8754-8b943006f895)

**Comment by MadOne** [comment]
@eddiewardoo : Can you post a screenshot of your values?

**Comment by OStrama** [comment]
Same here. The oonly difference I see is "HZ-Konfiguratio2" = aus. Maybe we have to check this?

**Comment by OStrama** [comment]
Otherwise, this is what we get back from the device. A user should know how many "Heizkreise" he has, so it should be possible to simply ignore them..

**Comment by MadOne** [comment]
Well i myself was not sure if i have one or two. 
Whats the point in having more than one? A screenshot or History of an active HK2 would help.

**Comment by OStrama** [comment]
Usually you have 2 or more, when you have different types of equipment in your house (radiators on one circuit, floor heater on the other) or if you have a house with some apartments. The plumber should have told you when doing the acceptance..

**Comment by OStrama** [comment]
Done in next version. Due to time reasons this version will have the possibility to select the number of "Heizkreise" during installation. Automatic detection will perhaps integrated in a future version.

**Comment by eddiewardoo** [comment]
Sorry for the delay if still interested, here is the screen shot
![image](https://github.com/user-attachments/assets/6305371b-bf98-40a5-8752-810af0a55c42)

**Comment by MadOne** [comment]
@eddiewardoo : 
Can you please check if HK 2 HZ_Konfiguration ever changes the value?

**Comment by eddiewardoo** [comment]
@MadOne does not change so far. Only become unavailable every once and a while.
Mischkreis
![image](https://github.com/user-attachments/assets/c6c7b58f-80f8-46a8-84a4-daffc69fccca)

Same with HM 1 HZ_Konfiguration
Sollwert (Pumpe M1)
![image](https://github.com/user-attachments/assets/14de0c60-3657-4556-8664-1371802393a6)

**Comment by OStrama** [comment]
I think the „Konfiguration“ values are all parameters that you can set on the heatpump in expert mode. So they probably will not change by themselves.
Perhaps there‘s a timeout when they get unavailable..

**Comment by MadOne** [comment]
Thats right. But i print them out for debugging. So i can change the configuration and get values in HA. I am currently working on the status items for them. So you can see what is configured for the input/output.

**Comment by eddiewardoo** [comment]
@OStrama @MadOne Can confirm. These can be changed when in Service or OEM mode on the controller.

**Comment by MadOne** [comment]
So we could check if it is set to anything but out  and then add the Heizkreis entities.
