### ISSUE TITLE
 Warmwasser Absenk and  Warmwasser Normal are not type "climate"

### ISSUE THREAD

**Issue by exp1338** [OStrama/weishaupt_modbus#9]
**Describe the bug**
 Warmwasser Absenk and  Warmwasser Normal are not type "climate"

**To Reproduce**
Look at the current entities in device "Warmwasser"

**Expected behavior**
Both entities should be type climate to change the value easly in automations.

Maybe you should change type of every climate entities like "number.raumsolltemperatur_absenk" and so on.

**Screenshots**
![Screenshot 2024-10-19 193927](https://github.com/user-attachments/assets/efead3e4-2e4c-44b9-9625-6ef9d6053f86)

**Additional context**

**Comment by MadOne** [comment]
What is holding you back to use this entity in automations?


![Bildschirmfoto vom 2024-10-19 20-20-07](https://github.com/user-attachments/assets/41d786e2-8edc-4582-8e61-12dc96d06012)

**Comment by exp1338** [comment]
Sorry i was trying to find this action but was not able. Thanks alot! Very helpful comment. 

I the past i was more familiar with using climate actions.

**Comment by OStrama** [comment]
Thanks, MadOne! (Before this I used a simple modbus integration via configuration.yaml. There the warm water temps were configured as climate. I thought that this is not really reflecting the idea of these values. The temps are not intended to be used for changing the values manually, but as a parameter to be used in the timer programs.)
